### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'get'

### ISSUE THREAD

**Issue by MyJumperBroke23** [eloialonso/iris#22]
I'm trying to launch a training run, but when I run the command, I get the following error:

```
Traceback (most recent call last):
  File "src/main.py", line 4, in <module>
    from trainer import Trainer
  File "/work/ahsia/autoexperiment_dataset/iris/src/trainer.py", line 17, in <module>
    from agent import Agent
  File "/work/ahsia/autoexperiment_dataset/iris/src/agent.py", line 7, in <module>
    from models.actor_critic import ActorCritic
  File "/work/ahsia/autoexperiment_dataset/iris/src/models/actor_critic.py", line 14, in <module>
    from envs.world_model_env import WorldModelEnv
  File "/work/ahsia/autoexperiment_dataset/iris/src/envs/__init__.py", line 2, in <module>
    from .wrappers import make_atari, ResizeObsWrapper
  File "/work/ahsia/autoexperiment_dataset/iris/src/envs/wrappers.py", line 7, in <module>
    import gym
  File "/work/ahsia/anaconda3/envs/iris/lib/python3.7/site-packages/gym/__init__.py", line 13, in <module>
    from gym.envs import make, spec, register
  File "/work/ahsia/anaconda3/envs/iris/lib/python3.7/site-packages/gym/envs/__init__.py", line 10, in <module>
    _load_env_plugins()
  File "/work/ahsia/anaconda3/envs/iris/lib/python3.7/site-packages/gym/envs/registration.py", line 250, in load_env_plugins
    for plugin in metadata.entry_points().get(entry_point, []):
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by eloialonso** [comment]
Hi, can you make sure you are on the version of gym specified in the [requirements](https://github.com/eloialonso/iris/blob/main/requirements.txt)?
